"""Rename chd_rate to chf_rate

Revision ID: 08d3aaeca971
Revises: d0c0721c294b
Create Date: 2022-07-05 11:40:17.412908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d3aaeca971'
down_revision = 'd0c0721c294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates_table', sa.Column('chf_rate', sa.Float(), nullable=True))
    op.drop_column('rates_table', 'chd_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates_table', sa.Column('chd_rate', sa.FLOAT(), nullable=True))
    op.drop_column('rates_table', 'chf_rate')
    # ### end Alembic commands ###
